import { useState, useMemo, useCallback } from 'react'
import type { DimensionConfig } from './types'
import type { ExportTabId } from './export'
import { DEFAULT_CONFIG, DIMENSION_PRESETS } from './presets'
import { generateScale } from './scale-engine'
import { EXPORT_TABS, getExportContent } from './export'
import { ScaleControls } from './ScaleControls'
import { TokenTable } from './TokenTable'
import { ScaleRuler } from './ScaleRuler'
import { CurveEditor } from './CurveEditor'
import { SampleDesign } from './SampleDesign'
import { ScaleComparison } from './ScaleComparison'
import { FluidPreview } from './FluidPreview'
import { SectionHeading } from '@/components/SectionHeading'
import { Pill } from '@/components/Pill'
import { CopyButton } from '@/components/CopyButton'
import { Code } from '@/components/Code'

export default function DimensionPage() {
  const [config, setConfig] = useState<DimensionConfig>(DEFAULT_CONFIG)
  const [activePreset, setActivePreset] = useState<string | null>(null)
  const [exportTab, setExportTab] = useState<ExportTabId>('css')
  const [exportCopied, setExportCopied] = useState(false)

  const tokens = useMemo(() => generateScale(config), [config])

  const handleChange = useCallback((partial: Partial<DimensionConfig>) => {
    setConfig(prev => ({ ...prev, ...partial }))
    setActivePreset(null)
  }, [])

  const handlePresetChange = useCallback((presetId: string) => {
    const preset = DIMENSION_PRESETS.find(p => p.id === presetId)
    if (preset) {
      setConfig(prev => ({ ...prev, ...preset.config }))
      setActivePreset(presetId)
    }
  }, [])

  const handleLock = useCallback((index: number, value: number) => {
    setConfig(prev => ({
      ...prev,
      lockedTokens: { ...prev.lockedTokens, [index]: value },
    }))
    setActivePreset(null)
  }, [])

  const handleUnlock = useCallback((index: number) => {
    setConfig(prev => {
      const { [index]: _, ...rest } = prev.lockedTokens
      return { ...prev, lockedTokens: rest }
    })
    setActivePreset(null)
  }, [])

  const exportContent = useMemo(
    () => getExportContent(exportTab, tokens, config),
    [exportTab, tokens, config],
  )

  const handleExportCopy = useCallback(() => {
    navigator.clipboard.writeText(exportContent)
    setExportCopied(true)
    setTimeout(() => setExportCopied(false), 2000)
  }, [exportContent])

  return (
    <>
      {/* Hero: Curve Editor + Scale Ruler */}
      <div className="mt-2 sm:mt-4">
        <CurveEditor config={config} tokens={tokens} onChange={handleChange} />
        <ScaleRuler tokens={tokens} />
      </div>

      {/* Controls Panel */}
      <div className="mt-3 sm:mt-4">
        <ScaleControls
          config={config}
          activePreset={activePreset}
          onChange={handleChange}
          onPresetChange={handlePresetChange}
        />
      </div>

      {/* Token Table */}
      <div className="mt-6 sm:mt-8">
        <TokenTable
          tokens={tokens}
          config={config}
          onLock={handleLock}
          onUnlock={handleUnlock}
        />
      </div>

      {/* Sample Design */}
      <div className="mt-8 sm:mt-12">
        <SampleDesign tokens={tokens} />
      </div>

      {/* ─── Explanation Section ─── */}
      <div className="mt-10 sm:mt-20">
        <div className="border-t border-zinc-100 dark:border-zinc-700/40" />

        <h2 className="mt-8 text-2xl font-bold tracking-tight text-zinc-800 dark:text-zinc-100 sm:mt-12 sm:text-3xl">
          How It Works
        </h2>

        {/* Zone 1: Understanding */}
        <div className="mt-8 sm:mt-12 space-y-8 sm:space-y-10">
          <section className="space-y-4">
            <SectionHeading number="01" title="Why Scales Matter" id="why-scales-matter" />
            <div className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed max-w-2xl space-y-3">
              <p>
                A spacing scale is the backbone of visual consistency. Without one, every margin,
                padding, and gap is an ad-hoc decision. With one, every spacing value has a name,
                a reason, and a relationship to every other value.
              </p>
              <p>
                The scale is generated by a{' '}
                <span className="text-zinc-900 dark:text-zinc-100">progression function</span>{' '}
                that maps step indices to pixel values. The simplest is linear (multiply by a constant).
                More sophisticated scales use exponential growth, custom bezier curves, or harmonic ratios
                to concentrate fine-grained control where it matters most &mdash; at the small end.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <SectionHeading number="02" title="The Curve" id="the-curve" />
            <div className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed max-w-2xl space-y-3">
              <p>
                The curve editor above controls how values are distributed across the scale.
                Each step position is normalized to <Code>t = 0..1</Code>, then mapped through the
                curve function before computing the final value:
              </p>
              <p className="font-mono text-xs text-zinc-500 dark:text-zinc-400 bg-zinc-50 dark:bg-zinc-800/50 rounded-lg px-3 py-2">
                value = base &times; factor<sup>curve(t) &times; (steps - 1)</sup>
              </p>
              <p>
                A linear curve distributes steps evenly. An ease-in curve bunches values at the
                small end (more fine-grained control for tight spacing). An ease-out curve does the
                opposite. Drag the control points to create your own distribution.
              </p>
            </div>
          </section>

          {/* Scale Comparison */}
          <section className="space-y-4">
            <SectionHeading number="03" title="Compare" id="compare" />
            <div className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed max-w-2xl">
              <p>
                See how your scale stacks up against popular design systems.
              </p>
            </div>
            <div className="mt-4">
              <ScaleComparison tokens={tokens} />
            </div>
          </section>
        </div>

        {/* Zone divider */}
        <div className="border-t border-zinc-100 dark:border-zinc-700/40 mt-12 sm:mt-16" />

        {/* Zone 2: Technical */}
        <div className="mt-10 sm:mt-14 space-y-8 sm:space-y-10">
          {/* Fluid Tokens */}
          {config.fluid && (
            <section className="space-y-4">
              <SectionHeading number="04" title="Fluid Tokens" id="fluid-tokens" />
              <div className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed max-w-2xl space-y-3">
                <p>
                  Fluid tokens use <Code>clamp()</Code> to interpolate between a minimum and maximum
                  value based on the viewport width. This eliminates breakpoints for spacing &mdash;
                  values scale smoothly from <Code>{config.viewportMin}px</Code> to{' '}
                  <Code>{config.viewportMax}px</Code>.
                </p>
              </div>
              <div className="mt-4">
                <FluidPreview tokens={tokens} config={config} />
              </div>
            </section>
          )}

          {/* Export */}
          <section className="space-y-4">
            <SectionHeading number={config.fluid ? '05' : '04'} title="Export" id="export" />
            <div className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed max-w-2xl">
              <p>Copy your scale in the format your project needs.</p>
            </div>

            {/* Tab bar */}
            <div className="flex items-center gap-1.5 flex-wrap">
              {EXPORT_TABS.map((tab) => (
                <Pill
                  key={tab.id}
                  active={exportTab === tab.id}
                  onClick={() => setExportTab(tab.id)}
                  size="sm"
                >
                  {tab.label}
                </Pill>
              ))}
            </div>

            {/* Code block */}
            <div className="relative rounded-xl bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-100 dark:border-zinc-700/40 overflow-hidden">
              <div className="absolute top-2 right-2">
                <CopyButton copied={exportCopied} onClick={handleExportCopy} />
              </div>
              <pre className="p-4 text-xs font-mono text-zinc-700 dark:text-zinc-300 overflow-x-auto whitespace-pre leading-relaxed">
                {exportContent}
              </pre>
            </div>
          </section>
        </div>
      </div>
    </>
  )
}
